rest:
  - resource: "http://192.168.1.2/config"
    authentication: basic
    username: "admin"
    password: "admin"
    sensor:
      - name: "OnOff Status"
        value_template: "{{ value_json['OnOff'] }}"
      - name: "Output Config"
        value_template: "{{ value_json['OutputConfig'] }}"
      - name: "Charge Config"
        value_template: "{{ value_json['ChargeConfig'] }}"
      - name: "Uti Out Start"
        value_template: "{{ value_json['UtiOutStart'] }}"
      - name: "Uti Out End"
        value_template: "{{ value_json['UtiOutEnd'] }}"
      - name: "Uti Charge Start"
        value_template: "{{ value_json['UtiChargeStart'] }}"
      - name: "Uti Charge End"
        value_template: "{{ value_json['UtiChargeEnd'] }}"
      - name: "PV Model"
        value_template: "{{ value_json['PVModel'] }}"
      - name: "AC In Model"
        value_template: "{{ value_json['ACInModel'] }}"
      - name: "LCD Language"
        value_template: "{{ value_json['LCDLanguage'] }}"
      - name: "Output Voltage Type"
        value_template: "{{ value_json['OutputVoltType'] }}"
      - name: "Output Frequency Type"
        value_template: "{{ value_json['OutputFreqType'] }}"
      - name: "Overload Restart"
        value_template: "{{ value_json['OverLoadRestart'] }}"
      - name: "Overtemperature Restart"
        value_template: "{{ value_json['OverTempRestart'] }}"
      - name: "Buzzer Enable"
        value_template: "{{ value_json['BuzzerEnable'] }}"
      - name: "Serial Number"
        value_template: "{{ value_json['SerialNumber'] }}"
      - name: "Communication Address"
        value_template: "{{ value_json['ComAddress'] }}"
      - name: "Flash Start"
        value_template: "{{ value_json['FlashStart'] }}"
      - name: "Reset User Info"
        value_template: "{{ value_json['ResetUserInfo'] }}"
      - name: "Reset to Factory"
        value_template: "{{ value_json['ResetToFactory'] }}"
      - name: "Max Charge Amps"
        value_template: "{{ value_json['MaxChargeAmps'] }}"
      - name: "Bulk Charge Voltage"
        value_template: "{{ value_json['BulkChargeVolt'] }}"
      - name: "Float Charge Voltage"
        value_template: "{{ value_json['FloatChargeVolt'] }}"
      - name: "Battery Low to Utility"
        value_template: "{{ value_json['BatLowtoUti'] }}"
      - name: "AC Charge Amps"
        value_template: "{{ value_json['ACChargeAmps'] }}"
      - name: "Battery Type"
        value_template: "{{ value_json['BatteryType'] }}"
      - name: "Aging Mode"
        value_template: "{{ value_json['AgingMode'] }}"
      - name: "Function Mask"
        value_template: "{{ value_json['FunctionMask'] }}"
      - name: "Safety Type"
        value_template: "{{ value_json['SafetyType'] }}"
      - name: "DTC"
        value_template: "{{ value_json['DTC'] }}"
      - name: "System Year"
        value_template: "{{ value_json['SysYear'] }}"
      - name: "System Month"
        value_template: "{{ value_json['SysMonth'] }}"
      - name: "System Day"
        value_template: "{{ value_json['SysDay'] }}"
      - name: "System Hour"
        value_template: "{{ value_json['SysHour'] }}"
      - name: "System Minute"
        value_template: "{{ value_json['SysMin'] }}"
      - name: "System Second"
        value_template: "{{ value_json['SysSec'] }}"
      - name: "Utility AC Voltage High Limit"
        value_template: "{{ value_json['uwAcVoltHighL'] }}"
      - name: "Utility AC Voltage Low Limit"
        value_template: "{{ value_json['uwAcVoltLowL'] }}"
      - name: "Utility AC Frequency High Limit"
        value_template: "{{ value_json['uwAcFreqHighL'] }}"
      - name: "Utility AC Frequency Low Limit"
        value_template: "{{ value_json['uwAcFreqLowL'] }}"
      - name: "System Weekly"
        value_template: "{{ value_json['SysWeekly'] }}"
      - name: "Rated Watt"
        value_template: "{{ value_json['RateWatt'] }}"
      - name: "Rated VA"
        value_template: "{{ value_json['RateVA'] }}"
      - name: "Communication Board Version"
        value_template: "{{ value_json['ComboardVer'] }}"
      - name: "Battery Piece Number"
        value_template: "{{ value_json['uwBatPieceNum'] }}"
      - name: "Battery Low Cutoff"
        value_template: "{{ value_json['wBatLowCutOff'] }}"
      - name: "Utility AC to Battery Voltage"
        value_template: "{{ value_json['uwAC2BatVolt'] }}"
      - name: "Bypass Enable"
        value_template: "{{ value_json['BypEnable'] }}"
      - name: "Power Saving Enable"
        value_template: "{{ value_json['PowSavingEnable'] }}"
      - name: "Solar Power Balance Enable"
        value_template: "{{ value_json['SpowBalEnable'] }}"
      - name: "Clear Energy Today"
        value_template: "{{ value_json['ClrEnergyToday'] }}"
      - name: "Clear Energy All"
        value_template: "{{ value_json['ClrEnergyAll'] }}"
      - name: "Burn-in Test Enable"
        value_template: "{{ value_json['BurnInTestEnable'] }}"
      - name: "Manual Start Enable"
        value_template: "{{ value_json['ManualStartEnable'] }}"
      - name: "SCI Loss Check Enable"
        value_template: "{{ value_json['SciLossChkEnable'] }}"
      - name: "Backlight Enable"
        value_template: "{{ value_json['BlightEnable'] }}"
      - name: "Parallel Maximum Charge Amps"
        value_template: "{{ value_json['ParaMaxChgAmps'] }}"
      - name: "Lithium Protocol Type"
        value_template: "{{ value_json['LiProtocolType'] }}"
      - name: "Audio Alarm Enable"
        value_template: "{{ value_json['AudioAlarmEnable'] }}"
      - name: "Equalization Enable"
        value_template: "{{ value_json['uwEqEnable'] }}"
      - name: "Equalization Charge Voltage"
        value_template: "{{ value_json['uwEqChgVolt'] }}"
      - name: "Equalization Time"
        value_template: "{{ value_json['uwEqTime'] }}"
      - name: "Equalization Timeout"
        value_template: "{{ value_json['uwEqTimeOut'] }}"
      - name: "Equalization Interval"
        value_template: "{{ value_json['uwEqInterval'] }}"
      - name: "Maximum Discharge Amps"
        value_template: "{{ value_json['uwMaxDisChgAmps'] }}"
